apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb"  }}
  labels: {{- include "ccagc.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ required "A MySQL Database Password is required!" .Values.externalDatabase.password | b64enc | quote }}
