{{- if .Values.ingressRoute.enabled -}}
{{- $fullName := include "ccagc.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect-{{ $fullName }}
  labels:
    {{- include "ccagc.labels" . | nindent 4 }}
  {{- with .Values.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
