{{- if .Values.ingressRoute.enabled -}}
{{- $fullName := include "ccagc.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $Host := .Values.ingressRoute.host -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-{{ $fullName }}
  labels:
    {{- include "ccagc.labels" . | nindent 4 }}
  {{- with .Values.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ $Host }}`) && PathPrefix(`/agc/`)
    kind: Rule
    services:
    - name: {{ $fullName }}
      port: {{ $svcPort }}
  {{- if .Values.ingressRoute.tls.enabled }}
  tls:
    secretName: {{ printf "%s-%s" .Release.Name "tls-le"  }}
  {{- end }}
{{- end }}
